### ISSUE TITLE
Not opening - could be due to Java 8?

### ISSUE THREAD

**Issue by neuhausr** [nvkelso/color-oracle-java#5]
Color Oracle worked fine for me a few weeks ago, but isn't now. I notice that my computer updated to Java 8, and all the documentation says Color Oracle works for Java 6 or 7. Has Java 8 broken something with Color Oracle?

**Comment by nvkelso** [comment]
Will have a look, but will take a couple weeks.

**Comment by neuhausr** [comment]
thanks!

**Comment by neuhausr** [comment]
Tried using it again recently and it's working fine for me, so closing this issue.

**Comment by geospatialem** [comment]
I recently upgraded to a new JDK (*Java 8, Update 51*), and it appears that it 'broke' my Color Oracle as I'm getting the following message: 

![colorOracleError](https://cloud.githubusercontent.com/assets/5023024/8882628/1235330e-320e-11e5-9941-c5f28d487a7a.JPG)

I updated my JAVA_Home, so I'm not sure what the issue is.

@nvkelso - ever see anything like this before?

**Comment by nvkelso** [comment]
Color Oracle should work with Java 8. It might be initially hidden in the
Windows task bar. If you cannot find it, we recommend you re-install Java.

**Comment by geospatialem** [comment]
Thanks @nvkelso, the uninstall/reinstall did the trick!
